// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import ()

type ChallengeEvent struct {
	ID        int64  `db:"id" json:"id"`
	Hash      string `db:"hash" json:"hash"`
	Block     int32  `db:"block" json:"block"`
	Timestamp int32  `db:"timestamp" json:"timestamp"`
	Amount    string `db:"amount" json:"amount"`
	From      string `db:"from" json:"from"`
}
