// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (ChallengeEvent, error)
	ListEvents(ctx context.Context) ([]ChallengeEvent, error)
}

var _ Querier = (*Queries)(nil)
