services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT_EXTERNAL}:${DATABASE_PORT_INTERNAL}
    volumes:
      - ./:/challenge/
    environment:
      - POSTGRES_DB=${DATABASE_POSTGRES_DB}
      - POSTGRES_USER=${DATABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
      - TIMESCALEDB_TELEMETRY=${DATABASE_TIMESCALEDB_TELEMETRY}
